// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBRNGCmeMJl1o2dZCv9b0CPXrwG1Gxjw',
    appId: '1:388575517095:android:6df1805fc426ac65973e82',
    messagingSenderId: '388575517095',
    projectId: 'flutter-sample-c577f',
    storageBucket: 'flutter-sample-c577f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEwNJn7vxL1EtLDkrqjHIU0zVaEKV32IE',
    appId: '1:388575517095:ios:4aa6d488d62fb9f0973e82',
    messagingSenderId: '388575517095',
    projectId: 'flutter-sample-c577f',
    storageBucket: 'flutter-sample-c577f.firebasestorage.app',
    androidClientId: '388575517095-7en7ecrh3fuv5jtsugjpclic1v8bt4et.apps.googleusercontent.com',
    iosClientId: '388575517095-vvc83epc5al9rg32lcbs78prvd3o5fub.apps.googleusercontent.com',
    iosBundleId: 'com.example.airBnbClone',
  );

}